name: Windows release

on:
  workflow_run:
    workflows: ["Release setup"]
    types: [completed]

jobs:
  buildWindows:
    if: "!contains(github.event.commits[0].message, '!minor')"
    runs-on: ubuntu-latest

    steps:
    
    - name: Job info
      run: |
        echo "GitHub Ref: ${{ github.ref }}"
        echo "Event: ${{ github.event }}"
    
    - name: checkout sources
      uses: actions/checkout@v2

        #- name: Install sudo package
        #run:  apt update && apt install sudo
    
    - name: build_all_static
      run: |
        ./picsimlab_build_w64.sh
        ./picsimlab_build_w32.sh

    - name: package artifacts
      run: |
        ./picsimlab_build_windows_zip.sh
        ./picsimlab_build_windows_zip.sh exp

    - uses: actions/upload-artifact@v2
      with:
        name: picsimlab_pkg
        path: release*/*

    - name: Latest code build release
      uses: softprops/action-gh-release@v1
      if: github.ref == 'refs/heads/master' 
      with:
        prerelease: true
        files: release_*/*
        tag_name: latestbuild
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - if: (startsWith(github.ref, 'refs/tags/')) 
      name: tagged release
      uses: softprops/action-gh-release@v1
      with:
        files: release_*/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

